# =============================================================================
# templates/configmap.yaml — Template Helm pour le ConfigMap
# =============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: mini-config
data:
  DB_HOST: postgres
