# =============================================================================
# templates/deployment.yaml — Template Helm pour le Deployment API
# =============================================================================
#
# TEMPLATING HELM :
# - {{ .Values.image.repository }}:{{ .Values.image.tag }} : image Docker
# - {{ .Values.image.pullPolicy }} : politique de pull
# =============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini
      tier: api
  template:
    metadata:
      labels:
        app: mini
        tier: api
    spec:
      containers:
        - name: api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mini-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mini-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mini-secrets
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mini-config
                  key: DB_HOST
            - name: DATABASE_URL
              value: "postgresql+psycopg2://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):5432/$(DB_NAME)"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mini-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
